function [IncrementID,vMisesEqvTrueStrain,vMisesEqCauchyStress] = read_flowcurve_damaskpdt(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [INCREMENTID,VMISESEQVTRUESTRAIN,VMISESEQCAUCHYSTRESS] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [INCREMENTID,VMISESEQVTRUESTRAIN,VMISESEQCAUCHYSTRESS] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [IncrementID,vMisesEqvTrueStrain,vMisesEqCauchyStress] = importfile('DAMASKPDT.SimID.10136.Incr.0.1.415.Incr.All.Flowcurve.csv',3, 30);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/05/26 11:28:02

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format for each line of text:
%   column3: double (%f)
%	column50: double (%f)
%   column51: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
IncrementID = dataArray{:, 1};
vMisesEqvTrueStrain = dataArray{:, 2};
vMisesEqCauchyStress = dataArray{:, 3};


